[package]
name = "avila-pdf"
version = "0.1.0"
edition = "2021"
authors = ["Nícolas Ávila <avilaops@gmail.com>"]
description = "Native PDF generation - Zero external dependencies"
license = "MIT OR Apache-2.0"

[dependencies]
# Zero external dependencies
